// Private fields with public constructor params need explicit initializers.
// ignore_for_file: prefer_initializing_formals
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:hermes_client/hermes_client.dart';

import 'cliproxy_binary.dart';
import 'errors.dart';
import 'supervisor.dart';

/// Well-known [SecretStore] keys for the CLIProxyAPI sidecar, stored under
/// the [cliproxyInstanceId] pseudo-instance.
abstract final class CliproxySecretKeys {
  /// `remote-management.secret-key` (plaintext in the generated config; the
  /// server hashes it on startup).
  static const managementKey = 'cliproxy_management_key';

  /// Bearer key Hermes presents on the sidecar's `/v1/*` inference routes.
  static const apiKey = 'cliproxy_api_key';
}

/// Pseudo-instance id under which the sidecar keys live in the [SecretStore].
const cliproxyInstanceId = 'cliproxy';

/// Generates the CLIProxyAPI YAML config Hermuse supervises.
///
/// Schema follows `config.example.yaml` of CLIProxyAPI v7.3.18: loopback
/// `host`, explicit `port`, `auth-dir`, `api-keys`, and `remote-management`
/// with `allow-remote: false` plus the plaintext `secret-key` the server
/// hashes on startup. The YAML is emitted by hand (no yaml dependency in the
/// shipped package): values are scalar and quoted with JSON string escaping,
/// which YAML accepts.
String buildCliproxyConfig({
  required int port,
  required String authDir,
  required String apiKey,
  required String managementKey,
}) {
  final q = jsonEncode;
  return '''
# Generated by Hermuse. Do not edit: overwritten on every sidecar start.
host: "127.0.0.1"
port: $port
auth-dir: ${q(authDir)}
api-keys:
  - ${q(apiKey)}
remote-management:
  allow-remote: false
  secret-key: ${q(managementKey)}
  disable-control-panel: true
discovery:
  enabled: false
''';
}

/// Supervises the CLIProxyAPI sidecar that bridges subscription accounts
/// (Claude Pro/Max, Meta, …) into Hermes as an OpenAI-compatible
/// endpoint.
///
/// The sidecar starts lazily via [ensureStarted] (first bridge card or login),
/// binds loopback on a free port with a generated config, and is verified
/// against `cliproxy.lock` before the first launch ([CliproxyBinary]).
/// Readiness is an authenticated `GET /v0/management/config` probe — the
/// route only exists once the management key is configured
/// (`server.go hasManagementSecret`). Remote management stays disabled
/// (`allow-remote: false`); both keys are random per install and live in the
/// [SecretStore], never on disk outside the 0600 config file.
final class CliproxySupervisor {
  CliproxySupervisor({
    required SecretStore secrets,
    required String hermesHome,
    Future<CliproxyBinary> Function()? locateBinary,
    Supervisor Function({
      required String executable,
      required List<String> args,
      Map<String, String>? environment,
    })?
    supervisorFactory,
    Future<bool> Function(Uri url, String managementKey)? probe,
  }) : _secrets = secrets,
       _hermesHome = hermesHome,
       _locateBinary = locateBinary ?? CliproxyBinary.locate,
       _supervisorFactory =
           supervisorFactory ??
           (({required executable, required args, environment}) => Supervisor(
             executable: executable,
             arguments: args,
             environment: environment,
           )),
       _probe = probe ?? _probeDefault;

  final SecretStore _secrets;
  final String _hermesHome;
  final Future<CliproxyBinary> Function() _locateBinary;
  final Supervisor Function({
    required String executable,
    required List<String> args,
    Map<String, String>? environment,
  })
  _supervisorFactory;
  final Future<bool> Function(Uri, String) _probe;

  Supervisor? _supervisor;
  Uri? _baseUrl;
  String? _apiKey;
  String? _managementKey;
  String? _configPath;

  /// Sidecar origin once [ensureStarted] succeeded.
  Uri? get baseUrl => _baseUrl;

  /// Bearer key for the sidecar's `/v1/*` routes (goes into the Hermes
  /// custom-endpoint body).
  String? get apiKey => _apiKey;

  /// Key for the `/v0/management/*` API (used with `CliproxyManagement`).
  String? get managementKey => _managementKey;

  /// Path of the generated sidecar config; null until [ensureStarted].
  String? get configPath => _configPath;

  SupervisorState get state => _supervisor?.state ?? SupervisorState.stopped;

  Stream<SupervisorState> get stateChanges =>
      _supervisor?.stateChanges ?? const Stream.empty();

  Stream<SupervisorLog> get logs => _supervisor?.logs ?? const Stream.empty();

  /// Starts the sidecar unless it is already running. Resolves the keys
  /// (generating and storing them on first run), writes the config, spawns
  /// the verified binary, and waits for the management probe.
  Future<Uri> ensureStarted() async {
    if (_supervisor?.isRunning ?? false) return _baseUrl!;
    final binary = await _locateBinary();
    _managementKey = await _resolveKey(CliproxySecretKeys.managementKey);
    _apiKey = await _resolveKey(CliproxySecretKeys.apiKey);
    final port = await _freePort();
    final authDir = await _ensureAuthDir();
    final configPath = _configPathFor();
    final config = buildCliproxyConfig(
      port: port,
      authDir: authDir,
      apiKey: _apiKey!,
      managementKey: _managementKey!,
    );
    // The config embeds both keys: its directory is 0700 (see
    // [_ensureAuthDir]) before the file exists, so no other user can read it
    // in the window before the file itself is narrowed to 0600.
    final configFile = File(configPath);
    await configFile.writeAsString(config);
    if (!Platform.isWindows) await _chmod('600', configPath);
    _configPath = configPath;
    _baseUrl = Uri.parse('http://127.0.0.1:$port');

    final supervisor = _supervisorFactory(
      executable: binary.path,
      args: ['-config', configPath],
    );
    _supervisor = supervisor;
    await supervisor.start();
    final ready = await _waitReady(_baseUrl!, _managementKey!);
    if (!ready) {
      final tail = supervisor.outputTail.join('\n');
      await supervisor.stop();
      throw ProcessFailed(
        'CLIProxyAPI sidecar never answered the management probe',
        outputTail: tail,
      );
    }
    return _baseUrl!;
  }

  /// Stops the sidecar. Idempotent.
  Future<void> stop() async {
    await _supervisor?.stop();
  }

  Future<void> dispose() async {
    await _supervisor?.dispose();
    _supervisor = null;
  }

  Future<String> _resolveKey(String key) async {
    final existing = await _secrets.read(cliproxyInstanceId, key);
    if (existing != null && existing.isNotEmpty) return existing;
    final fresh = _mintKey();
    await _secrets.write(cliproxyInstanceId, key, fresh);
    return fresh;
  }

  /// 32 random bytes, base64url without padding.
  static String _mintKey() {
    final random = Random.secure();
    final bytes = List<int>.generate(32, (_) => random.nextInt(256));
    return base64Url.encode(bytes).replaceAll('=', '');
  }

  Future<String> _ensureAuthDir() async {
    final sep = Platform.pathSeparator;
    final dir = Directory('$_hermesHome${sep}cliproxy${sep}auth');
    await dir.create(recursive: true);
    if (!Platform.isWindows) {
      await _chmod('700', dir.parent.path);
      await _chmod('700', dir.path);
    }
    return dir.path;
  }

  static Future<void> _chmod(String mode, String path) async {
    final result = await Process.run('chmod', [mode, path]);
    if (result.exitCode != 0) {
      throw ProcessFailed('chmod $mode $path failed: ${result.stderr}');
    }
  }

  String _configPathFor() {
    final sep = Platform.pathSeparator;
    return '$_hermesHome${sep}cliproxy${sep}config.yaml';
  }

  static Future<int> _freePort() async {
    final socket = await ServerSocket.bind(InternetAddress.loopbackIPv4, 0);
    final port = socket.port;
    await socket.close();
    return port;
  }

  Future<bool> _waitReady(Uri base, String key) async {
    final deadline = DateTime.now().add(const Duration(seconds: 30));
    while (DateTime.now().isBefore(deadline)) {
      if (await _probe(base, key)) return true;
      await Future<void>.delayed(const Duration(milliseconds: 250));
    }
    return false;
  }

  static Future<bool> _probeDefault(Uri base, String key) async {
    final client = HttpClient();
    try {
      final request = await client.getUrl(base.resolve('v0/management/config'));
      request.headers.set('Authorization', 'Bearer $key');
      final response = await request.close().timeout(
        const Duration(seconds: 2),
      );
      await response.drain();
      return response.statusCode == 200;
    } catch (_) {
      return false;
    } finally {
      client.close();
    }
  }
}
