// Builds the bounded Linux helper with an immutable plugin snapshot inside it.
// Run from packages/hermuse_host; the release build invokes the same command.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

Future<void> main(List<String> arguments) async {
  if (!Platform.isLinux || arguments.isNotEmpty) {
    stderr.writeln('Usage (Linux): dart run tool/build_linux_service.dart');
    exitCode = 64;
    return;
  }
  final package = File.fromUri(Platform.script).parent.parent;
  final plugin = Directory(
    '${package.parent.parent.path}/hermes-plugin/hermuse',
  );
  final files = <String, File>{};
  await for (final entity in plugin.list(recursive: true, followLinks: false)) {
    final relative = entity.path.substring(plugin.path.length + 1);
    final parts = relative.split('/');
    if (parts.first == 'tests' ||
        parts.contains('__pycache__') ||
        parts.any((part) => part.startsWith('.'))) {
      continue;
    }
    if (entity is Link) {
      throw FileSystemException(
        'Plugin sources cannot contain symlinks.',
        entity.path,
      );
    }
    if (entity is File) {
      files[relative] = entity;
    }
  }
  if (!files.containsKey('plugin.yaml') || !files.containsKey('__init__.py')) {
    throw StateError('The canonical plugin source bundle is incomplete.');
  }
  final encoded = <String, String>{};
  for (final name in files.keys.toList()..sort()) {
    encoded[name] = base64Encode(await files[name]!.readAsBytes());
  }
  final snapshot = base64Encode(gzip.encode(utf8.encode(jsonEncode(encoded))));
  final directory = Directory('${package.path}/build/linux-service');
  await directory.create(recursive: true);
  final staging = await directory.createTemp('.build-');
  try {
    final entrypoint = File('${staging.path}/hermuse_linux_service.dart');
    await entrypoint.writeAsString(
      '''// Generated by tool/build_linux_service.dart. Do not edit.
import 'dart:convert';
import 'dart:io';
import 'package:hermuse_host/src/linux_service_helper.dart';

Future<void> main(List<String> arguments) async {
  exitCode = await runLinuxServiceHelper(arguments, base64Decode('$snapshot'));
}
''',
    );
    final binary = File('${staging.path}/hermuse-linux-service');
    final compile = await Process.start('dart', [
      'compile',
      'exe',
      entrypoint.path,
      '-o',
      binary.path,
    ], mode: ProcessStartMode.inheritStdio);
    final status = await compile.exitCode;
    if (status != 0) {
      exitCode = status;
      return;
    }
    final digest = '${await sha256.bind(binary.openRead()).first}';
    final checksum = File('${binary.path}.sha256');
    await checksum.writeAsString('$digest\n');
    final destination = '${directory.path}/hermuse-linux-service';
    // Replacing the inode permits rebuilds while an inspection uses the old ELF.
    await binary.rename(destination);
    await checksum.rename('$destination.sha256');
    stdout.writeln('$digest  $destination');
  } finally {
    await staging.delete(recursive: true);
  }
}
