#!/usr/bin/env bash
# Renders the native app icons of apps/hermuse_app (committed) from
# packaging/icon/icon.svg, the Hermuse mark: a yellow "h" on an ink tile, on a
# 512 grid (one <rect> tile, one <path> glyph). Run it after changing the icon;
# needs rsvg-convert (librsvg) and ImageMagick (`magick` or `convert`).
#
#   Android  mipmap-*/ic_launcher.png, the rounded tile (before Android 8), and
#            the adaptive icon: ink background, vector glyph as foreground and
#            monochrome layer, the 512 tile mapped onto the 72 dp visible area
#   iOS      every size of AppIcon.appiconset/Contents.json, full bleed, opaque
#   macOS    AppIcon.appiconset on Apple's grid: an 824 px rounded tile centred
#            in 1024 px, over a soft shadow
#   Windows  runner/resources/app_icon.ico, the rounded tile at 16-256 px
#   Linux    runner/resources/app_icon.png, the window icon the runner loads
#            from the bundle's data/; the .deb and AppImage render their
#            hicolor icons from icon.svg when packaging (render_icons in
#            packaging/linux/lib/common.sh)
set -euo pipefail

repo="$(cd "$(dirname "$0")/../.." && pwd)"
src="$repo/packaging/icon/icon.svg"
app="$repo/apps/hermuse_app"
for tool in rsvg-convert sed; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "render-app-icons: $tool is required" >&2
    exit 1
  }
done
if command -v magick >/dev/null 2>&1; then
  im=(magick)
elif command -v convert >/dev/null 2>&1; then
  im=(convert)
else
  echo "render-app-icons: ImageMagick (magick or convert) is required" >&2
  exit 1
fi

flat="$(tr -d '\n' <"$src")"
attr() { # <element> <attribute>
  sed -n "s/.*<$1[^>]* $2=\"\([^\"]*\)\".*/\1/p" <<<"$flat"
}
ink="$(attr rect fill)"
glyph_fill="$(attr path fill)"
glyph_d="$(attr path d)"
read -r glyph_x glyph_y < <(attr path transform | sed -n 's/^translate(\([^ ,]*\)[ ,]*\([^)]*\))$/\1 \2/p')
[ -n "$ink" ] && [ -n "$glyph_fill" ] && [ -n "$glyph_d" ] && [ -n "${glyph_y:-}" ] || {
  echo "render-app-icons: $src needs <rect fill> and <path fill transform=\"translate(x y)\" d>" >&2
  exit 1
}
glyph="<path fill=\"$glyph_fill\" transform=\"translate($glyph_x $glyph_y)\" d=\"$glyph_d\"/>"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cat >"$tmp/full-bleed.svg" <<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" fill="$ink"/>$glyph</svg>
SVG
cat >"$tmp/macos.svg" <<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <defs>
    <filter id="shadow" filterUnits="userSpaceOnUse" x="0" y="0" width="1024" height="1024">
      <feDropShadow dx="0" dy="10" stdDeviation="14" flood-color="#000000" flood-opacity="0.35"/>
    </filter>
  </defs>
  <rect x="100" y="100" width="824" height="824" rx="185" fill="$ink" filter="url(#shadow)"/>
  <svg x="100" y="100" width="824" height="824" viewBox="0 0 512 512">$glyph</svg>
</svg>
SVG

render() { # <svg> <size> <png>
  rsvg-convert -w "$2" -h "$2" "$1" -o "$3"
}

# Android: legacy launcher icons per density, then the adaptive icon (API 26+).
res="$app/android/app/src/main/res"
for density in mdpi:48 hdpi:72 xhdpi:96 xxhdpi:144 xxxhdpi:192; do
  render "$src" "${density#*:}" "$res/mipmap-${density%:*}/ic_launcher.png"
done
mkdir -p "$res/mipmap-anydpi-v26" "$res/drawable" "$res/values"
cat >"$res/mipmap-anydpi-v26/ic_launcher.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/icon/render-app-icons.sh. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
XML
cat >"$res/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/icon/render-app-icons.sh. -->
<resources>
    <color name="ic_launcher_background">$ink</color>
</resources>
XML
# 108 dp layer, 72 dp visible: the 512 tile maps onto the visible 72 dp, so a
# 768 viewport with the tile's origin at 128. The glyph stays well inside the
# 66 dp safe zone.
cat >"$res/drawable/ic_launcher_foreground.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/icon/render-app-icons.sh. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="768"
    android:viewportHeight="768">
    <group
        android:translateX="$(awk -v v="$glyph_x" 'BEGIN { print 128 + v }')"
        android:translateY="$(awk -v v="$glyph_y" 'BEGIN { print 128 + v }')">
        <path
            android:fillColor="$glyph_fill"
            android:pathData="$glyph_d" />
    </group>
</vector>
XML

# iOS: every file of Contents.json, sized from its name (Icon-App-<pt>x<pt>@<n>x.png),
# full bleed and without an alpha channel (App Store Connect rejects alpha).
ios="$app/ios/Runner/Assets.xcassets/AppIcon.appiconset"
sed -n 's/.*"filename" *: *"\([^"]*\)".*/\1/p' "$ios/Contents.json" | sort -u | while read -r name; do
  size="$(sed -n 's/^Icon-App-\([0-9.]*\)x[0-9.]*@\([0-9]\)x\.png$/\1 \2/p' <<<"$name" |
    awk '{ print $1 * $2 }')"
  [ -n "$size" ] || {
    echo "render-app-icons: unexpected iOS icon name $name" >&2
    exit 1
  }
  render "$tmp/full-bleed.svg" "$size" "$tmp/ios.png"
  "${im[@]}" "$tmp/ios.png" -background "$ink" -alpha remove -alpha off -strip "PNG24:$ios/$name"
done

# macOS (Big Sur template).
for size in 16 32 64 128 256 512 1024; do
  render "$tmp/macos.svg" "$size" "$app/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_$size.png"
done

# Windows: one .ico, each size rendered from the vector (not downscaled).
ico_pngs=()
for size in 16 20 24 32 40 48 64 96 128 256; do
  render "$src" "$size" "$tmp/ico-$size.png"
  ico_pngs+=("$tmp/ico-$size.png")
done
"${im[@]}" "${ico_pngs[@]}" "$app/windows/runner/resources/app_icon.ico"

# Linux: the window icon shipped in the bundle.
mkdir -p "$app/linux/runner/resources"
render "$src" 256 "$app/linux/runner/resources/app_icon.png"
